# This is a basic workflow to help you get started with Actions

name: Update Weather Badge

# Controls when the workflow will run
on:
  # Schedule the workflow to run daily at midnight UTC
  schedule:
   - cron: '0 0 * * *' # Schedule  

jobs:
  update-readme:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Check out code
        uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Fetch Weather Data
        run: |
          # Use your weather API and API key to fetch weather data
          curl "https://api.openweathermap.org/data/2.5/weather?q=QUEBEC CITY&appid=c540d8ba38658c6e999902bae1b0f703" -o weather.json 

      - name: Update README
        run: |
         # Parse weather data from weather.json and generate the badge URL
         WEATHER_BADGE="https://img.shields.io/badge/Weather-Quebec City-<blue.svg"
         WEATHER_INFO="Quebec City Weather: Sunny"
         sed -i "s|!\[Weather\].*|![Weather]($WEATHER_BADGE)|" README.md
         sed -i "s|<!-- WEATHER_INFO_START -->.*<!-- WEATHER_INFO_END -->|<!-- WEATHER_INFO_START -->$WEATHER_INFO<!-- WEATHER_INFO_END -->|" README.md

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update weather information"
          git push  
